[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.armv7a-none-eabi]
rustflags = ["-C", "link-arg=-Tlink.x"]
runner = "qemu-system-arm -M xilinx-zynq-a9 -s -S -nographic -kernel"

[build]
target = "armv7a-none-eabi"